### PR TITLE
fixed asset path to top banner dropdown arrow

### PR DESCRIPTION
**Pull request by ronald-bbg**

### CODE REVIEW

**Comment by ronald-bbg** [comment]
Pending va-website-template repo fixes...

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Somehow body text color got rolled back to #1b1b1b (some of text highlighted to show it's there, just dark text on dark background). Should be #fcfcfc.
image

**Comment by ronald-bbg** [comment]
this ready for approval

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Home:
ARIA:
- [role]s do not have all required [aria-*] attributes (masthead <p>)
- Values assigned to role="" are not valid ARIA roles. (awards buttons) Also, Buttons do not have an accessible name
- Links do not have a discernible name (Virtual Teleportation video)

**Review by ecstech-admin — APPROVED** [review]
Done!

**Pull request merged**
